apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sa-dataset-collector
  annotations:
    description: The Stock Analysis Dataset Collector
    runtime: python3
  labels:
    sa: engine
    purpose: stock-analysis
    layer: backend
    messaging: redis
    cache: redis
    pubsub: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sa-dataset-collector
      backend: enabled
  template:
    metadata:
      labels:
        app: sa-dataset-collector
        backend: enabled
        purpose: stock-analysis
        layer: backend
        messaging: redis
        cache: redis
        pubsub: publisher
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: backend
                operator: In
                values:
                - enabled
      hostname: sa-dataset-collector
      restartPolicy: Always
      containers:
      - image: jayjohnson/stock-analysis-engine:latest
        imagePullPolicy: Always
        name: sa-dataset-collector
        resources: {}
        command:
        - /bin/bash
        - -c
        - cd /opt/sa/ &&
          . /opt/venv/bin/activate &&
          /opt/sa/tools/start-dataset-collection.sh
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: api.db
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api.db
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: api.db
              key: dbname
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-s3-access
              key: access_key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-s3-access
              key: secret_key
        - name: S3_ADDRESS
          value: minio-service:9000
        - name: S3_REGION_NAME
          value: us-east-1
        - name: WORKER_BROKER_URL
          value: redis://redis-master:6379/13
        - name: WORKER_BACKEND_URL
          value: redis://redis-master:6379/14
        - name: REDIS_ADDRESS
          value: redis-master:6379
        - name: REDIS_DB
          value: "4"
        # Stock Analysis - Dataset Collector Envs:
        - name: S3_BUCKET
          value: pricing
        - name: DAILY_S3_BUCKET_NAME
          value: daily
        - name: MINUTE_S3_BUCKET_NAME
          value: minute
        - name: TICK_S3_BUCKET_NAME
          value: tick
        - name: STATS_S3_BUCKET_NAME
          value: stats
        - name: PEERS_S3_BUCKET_NAME
          value: peers
        - name: NEWS_S3_BUCKET_NAME
          value: news
        - name: FINANCIALS_S3_BUCKET_NAME
          value: financials
        - name: EARNINGS_S3_BUCKET_NAME
          value: earnings
        - name: DIVIDENDS_S3_BUCKET_NAME
          value: dividends
        - name: COMPANY_S3_BUCKET_NAME
          value: company
        - name: PREPARE_S3_BUCKET_NAME
          value: prepared
        - name: ANALYZE_S3_BUCKET_NAME
          value: analyzed
        - name: FETCH_MODE
          value: full
        - name: TICKER
          value: SPY
        - name: DEFAULT_TICKERS
          value: SPY,TSLA,AMZN,NFLX
