apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sa-engine
  annotations:
    description: The Stock Analysis Engine
    runtime: python3
  labels:
    sa: engine
    purpose: stock-analysis
    layer: backend
    messaging: redis
    cache: redis
    pubsub: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sa-engine
      backend: enabled
  template:
    metadata:
      labels:
        app: sa-engine
        backend: enabled
        purpose: stock-analysis
        layer: backend
        messaging: redis
        cache: redis
        pubsub: publisher
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: backend
                operator: In
                values:
                - enabled
      hostname: sa-engine
      restartPolicy: Always
      containers:
      - image: jayjohnson/stock-analysis-engine:latest
        imagePullPolicy: Always
        name: sa-engine
        resources: {}
        command:
        - /bin/bash
        - -c
        - cd /opt/sa/ &&
          . /opt/venv/bin/activate &&
          /opt/sa/start-workers.sh
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: api.db
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api.db
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: api.db
              key: dbname
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-s3-access
              key: access_key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-s3-access
              key: secret_key
        - name: S3_ADDRESS
          value: minio-service:9000
        - name: S3_REGION_NAME
          value: us-east-1
        - name: WORKER_BROKER_URL
          value: redis://redis-master:6379/13
        - name: WORKER_BACKEND_URL
          value: redis://redis-master:6379/14
        - name: REDIS_ADDRESS
          value: redis-master:6379
        - name: REDIS_DB
          value: "4"
        - name: DEPLOY_CONFIG
          value: splunk
        - name: LOG_NAME
          value: sa-engine
        - name: ENV_NAME
          value: k8
        - name: SPLUNK_USER
          valueFrom:
            secretKeyRef:
              name: splunk.user
              key: username
        - name: SPLUNK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: splunk.user
              key: password
        - name: SPLUNK_ADDRESS
          valueFrom:
            secretKeyRef:
              name: splunk.endpoints
              key: hec
        - name: SPLUNK_API_ADDRESS
          valueFrom:
            secretKeyRef:
              name: splunk.endpoints
              key: api
        - name: SPLUNK_TCP_ADDRESS
          valueFrom:
            secretKeyRef:
              name: splunk.endpoints
              key: tcp
        - name: SPLUNK_INDEX
          valueFrom:
            secretKeyRef:
              name: splunk.log
              key: index
        - name: SPLUNK_HANDLER_NAME
          valueFrom:
            secretKeyRef:
              name: splunk.log
              key: handler
        - name: SPLUNK_VERIFY
          valueFrom:
            secretKeyRef:
              name: splunk.log
              key: verify
        - name: SPLUNK_DEBUG
          valueFrom:
            secretKeyRef:
              name: splunk.log
              key: debug
